name: nzw9314-sync
on:
  schedule:
    - cron: '14 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-nzw9314-Loon
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync nzw9314-2020scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/nzw9314/Loon.git"
          source_branch: "master"
          destination_branch: "NZ9314"
          github_token: ${{ secrets.PAT }}
